################################################################
#
#
# Pipeline pipeline_quasar.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################
## general options


# Project name
projectname: CGATProject

# Copyright statement
copyright: CGAT (2010-2014)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

########################################################
# the genome to use (UCSC convention)
genome_fasta: /shared/sudlab1/General/mirror/genomes/plain/hg38_noalt.fasta

#input
snps_vcf: 1000G.vcf.gz
regions_of_high_mappability: /shared/sudlab1/General/projects/segmentation/chromHMM_excluded_regions/hg38_ENCODE_excluded_high_mappability_regions.bed.gz
regions_of_low_mappability: /shared/sudlab1/General/projects/segmentation/chromHMM_excluded_regions/hg38_ENCODE_excluded_regions_liftup_from_hg19.bed
regions_of_interest:


min_depth: 10
max_depth: 4000

database:
  name:
    

